version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build: ./backend
    command: node server.js
    ports:
      - "8000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always
